/**
 * Fare table.
 *
 * Fares are declared once per unordered stop pair and mirrored into a
 * symmetric lookup at module load. The previous nested-object matrix declared
 * 79 of its 105 pairs twice while omitting "Sector 30" and "Balco Medical
 * Center" from thirteen rows entirely - those journeys only priced correctly
 * because the lookup silently fell back to the reverse direction. Declaring
 * each pair once makes that class of gap impossible.
 */

import { STOPS, isStopName, type StopName } from "./stops";

type FarePair = readonly [StopName, StopName, number];

/**
 * Every unordered stop pair, exactly once. Grouped by price for readability.
 *
 * Values are the fares in rupees published in the official Tatpar BRTS fare
 * chart for Nava Raipur Atal Nagar.
 */
const FARE_PAIRS: readonly FarePair[] = [
  // ---- ₹5 ----
  ["HNLU", "Balco Medical Center", 5],
  ["HNLU", "Sector 30", 5],
  ["HNLU", "Sector 29", 5],
  ["HNLU", "Sector 27", 5],
  ["HNLU", "South Block", 5],
  ["HNLU", "Ekatm Path", 5],
  ["HNLU", "Mantri Aawas", 5],
  ["HNLU", "Rakhi Village", 5],
  ["HNLU", "Sector 27-29 Mid", 5],
  ["HNLU", "Jungle Safari", 5],
  ["HNLU", "HNLU Gate", 5],
  ["HNLU", "NH 30 Chowk", 5],
  ["HNLU", "IIIT", 5],
  ["HNLU", "Muktangan", 5],
  ["Balco Medical Center", "Sector 30", 5],
  ["Balco Medical Center", "Sector 29", 5],
  ["Balco Medical Center", "Sector 27", 5],
  ["Balco Medical Center", "South Block", 5],
  ["Balco Medical Center", "North Block", 5],
  ["Balco Medical Center", "Ekatm Path", 5],
  ["Balco Medical Center", "Mantri Aawas", 5],
  ["Balco Medical Center", "Rakhi Village", 5],
  ["Balco Medical Center", "Sector 27-29 Mid", 5],
  ["Balco Medical Center", "Jungle Safari", 5],
  ["Balco Medical Center", "HNLU Gate", 5],
  ["Balco Medical Center", "NH 30 Chowk", 5],
  ["Balco Medical Center", "IIIT", 5],
  ["Balco Medical Center", "Muktangan", 5],
  ["Sector 30", "Sector 29", 5],
  ["Sector 30", "Sector 27", 5],
  ["Sector 30", "South Block", 5],
  ["Sector 30", "Ekatm Path", 5],
  ["Sector 30", "IIM", 5],
  ["Sector 30", "Mantri Aawas", 5],
  ["Sector 30", "Rakhi Village", 5],
  ["Sector 30", "Sector 27-29 Mid", 5],
  ["Sector 30", "Jungle Safari", 5],
  ["Sector 30", "IIIT", 5],
  ["Sector 29", "Sector 27", 5],
  ["Sector 29", "South Block", 5],
  ["Sector 29", "Indravati Bhavan", 5],
  ["Sector 29", "Mahanadi Bhavan", 5],
  ["Sector 29", "North Block", 5],
  ["Sector 29", "Ekatm Path", 5],
  ["Sector 29", "CBD", 5],
  ["Sector 29", "IIM", 5],
  ["Sector 29", "Sector 17", 5],
  ["Sector 29", "CBD Railway Station", 5],
  ["Sector 29", "Office Complex Block A B", 5],
  ["Sector 29", "Mantri Aawas", 5],
  ["Sector 29", "Rakhi Village", 5],
  ["Sector 29", "Sector 27-29 Mid", 5],
  ["Sector 29", "Jungle Safari", 5],
  ["Sector 29", "HNLU Gate", 5],
  ["Sector 29", "IIIT", 5],
  ["Sector 29", "Muktangan", 5],
  ["Sector 27", "South Block", 5],
  ["Sector 27", "Indravati Bhavan", 5],
  ["Sector 27", "Mahanadi Bhavan", 5],
  ["Sector 27", "North Block", 5],
  ["Sector 27", "Ekatm Path", 5],
  ["Sector 27", "CBD", 5],
  ["Sector 27", "IIM", 5],
  ["Sector 27", "Sector 17", 5],
  ["Sector 27", "CBD Railway Station", 5],
  ["Sector 27", "Office Complex Block A B", 5],
  ["Sector 27", "Mantri Aawas", 5],
  ["Sector 27", "Rakhi Village", 5],
  ["Sector 27", "Sector 27-29 Mid", 5],
  ["Sector 27", "Jungle Safari", 5],
  ["Sector 27", "HNLU Gate", 5],
  ["Sector 27", "IIIT", 5],
  ["Sector 27", "Muktangan", 5],
  ["South Block", "Indravati Bhavan", 5],
  ["South Block", "Mahanadi Bhavan", 5],
  ["South Block", "North Block", 5],
  ["South Block", "Ekatm Path", 5],
  ["South Block", "CBD", 5],
  ["South Block", "Sector 15", 5],
  ["South Block", "Sector 17", 5],
  ["South Block", "Sector 22", 5],
  ["South Block", "CBD Railway Station", 5],
  ["South Block", "Office Complex Block A B", 5],
  ["South Block", "Mantri Aawas", 5],
  ["South Block", "Rakhi Village", 5],
  ["South Block", "Sector 27-29 Mid", 5],
  ["South Block", "IIIT", 5],
  ["Indravati Bhavan", "Mahanadi Bhavan", 5],
  ["Indravati Bhavan", "North Block", 5],
  ["Indravati Bhavan", "Ekatm Path", 5],
  ["Indravati Bhavan", "CBD", 5],
  ["Indravati Bhavan", "Sector 17", 5],
  ["Indravati Bhavan", "CBD Railway Station", 5],
  ["Indravati Bhavan", "Office Complex Block A B", 5],
  ["Indravati Bhavan", "Mantri Aawas", 5],
  ["Indravati Bhavan", "Rakhi Village", 5],
  ["Indravati Bhavan", "Sector 27-29 Mid", 5],
  ["Mahanadi Bhavan", "North Block", 5],
  ["Mahanadi Bhavan", "Ekatm Path", 5],
  ["Mahanadi Bhavan", "CBD", 5],
  ["Mahanadi Bhavan", "Sector 15", 5],
  ["Mahanadi Bhavan", "Sector 17", 5],
  ["Mahanadi Bhavan", "CBD Railway Station", 5],
  ["Mahanadi Bhavan", "Office Complex Block A B", 5],
  ["Mahanadi Bhavan", "Mantri Aawas", 5],
  ["Mahanadi Bhavan", "Rakhi Village", 5],
  ["Mahanadi Bhavan", "Sector 27-29 Mid", 5],
  ["North Block", "Ekatm Path", 5],
  ["North Block", "CBD", 5],
  ["North Block", "Sector 15", 5],
  ["North Block", "Sector 17", 5],
  ["North Block", "Satya Sai Hospital", 5],
  ["North Block", "Sector 22", 5],
  ["North Block", "CBD Railway Station", 5],
  ["North Block", "Office Complex Block A B", 5],
  ["North Block", "Mantri Aawas", 5],
  ["North Block", "Rakhi Village", 5],
  ["North Block", "Sector 27-29 Mid", 5],
  ["Ekatm Path", "CBD", 5],
  ["Ekatm Path", "Sector 15", 5],
  ["Ekatm Path", "Sector 17", 5],
  ["Ekatm Path", "Sector 22", 5],
  ["Ekatm Path", "CBD Railway Station", 5],
  ["Ekatm Path", "Office Complex Block A B", 5],
  ["Ekatm Path", "Mantri Aawas", 5],
  ["Ekatm Path", "Rakhi Village", 5],
  ["Ekatm Path", "Sector 27-29 Mid", 5],
  ["CBD", "Sector 15", 5],
  ["CBD", "Sector 17", 5],
  ["CBD", "Sector 22", 5],
  ["CBD", "CBD Railway Station", 5],
  ["CBD", "Office Complex Block A B", 5],
  ["CBD", "Mantri Aawas", 5],
  ["CBD", "Rakhi Village", 5],
  ["CBD", "Sector 27-29 Mid", 5],
  ["Sector 15", "Sector 17", 5],
  ["Sector 15", "Sector 22", 5],
  ["Sector 15", "CBD Railway Station", 5],
  ["Sector 15", "Office Complex Block A B", 5],
  ["Sector 15", "Mantri Aawas", 5],
  ["Sector 15", "Rakhi Village", 5],
  ["Telibandha", "DKS Bhawan", 5],
  ["Telibandha", "Agriculture College", 5],
  ["DKS Bhawan", "Raipur Railway Station", 5],
  ["IIM", "Sector 27-29 Mid", 5],
  ["Sector 17", "Satya Sai Hospital", 5],
  ["Sector 17", "Sector 22", 5],
  ["Sector 17", "CBD Railway Station", 5],
  ["Sector 17", "Office Complex Block A B", 5],
  ["Sector 17", "Mantri Aawas", 5],
  ["Sector 17", "Rakhi Village", 5],
  ["Sector 17", "Sector 27-29 Mid", 5],
  ["Satya Sai Hospital", "Stadium", 5],
  ["Satya Sai Hospital", "Nawagaon", 5],
  ["Stadium", "Nawagaon", 5],
  ["Sector 22", "CBD Railway Station", 5],
  ["Sector 22", "Office Complex Block A B", 5],
  ["Sector 22", "Mantri Aawas", 5],
  ["Sector 22", "IIIT", 5],
  ["Sector 22", "Muktangan", 5],
  ["CBD Railway Station", "Office Complex Block A B", 5],
  ["CBD Railway Station", "Mantri Aawas", 5],
  ["CBD Railway Station", "Rakhi Village", 5],
  ["CBD Railway Station", "Sector 27-29 Mid", 5],
  ["CBD Railway Station", "IIIT", 5],
  ["CBD Railway Station", "Muktangan", 5],
  ["Office Complex Block A B", "Mantri Aawas", 5],
  ["Office Complex Block A B", "Rakhi Village", 5],
  ["Office Complex Block A B", "Sector 27-29 Mid", 5],
  ["Office Complex Block A B", "IIIT", 5],
  ["Mantri Aawas", "Rakhi Village", 5],
  ["Mantri Aawas", "Sector 27-29 Mid", 5],
  ["Mantri Aawas", "IIIT", 5],
  ["Rakhi Village", "Sector 27-29 Mid", 5],
  ["Rakhi Village", "IIIT", 5],
  ["Rakhi Village", "Muktangan", 5],
  ["Sector 27-29 Mid", "Jungle Safari", 5],
  ["Sector 27-29 Mid", "HNLU Gate", 5],
  ["Sector 27-29 Mid", "IIIT", 5],
  ["Sector 27-29 Mid", "Muktangan", 5],
  ["Jungle Safari", "Rawatpura Sarkar University", 5],
  ["Jungle Safari", "HNLU Gate", 5],
  ["Jungle Safari", "IIIT", 5],
  ["Jungle Safari", "Muktangan", 5],
  ["Rawatpura Sarkar University", "Thanaud", 5],
  ["HNLU Gate", "NH 30 Chowk", 5],
  ["HNLU Gate", "IIIT", 5],
  ["HNLU Gate", "Muktangan", 5],
  ["NH 30 Chowk", "IIIT", 5],
  ["IIIT", "Muktangan", 5],

  // ---- ₹10 ----
  ["HNLU", "Indravati Bhavan", 10],
  ["HNLU", "Mahanadi Bhavan", 10],
  ["HNLU", "North Block", 10],
  ["HNLU", "CBD", 10],
  ["HNLU", "Sector 15", 10],
  ["HNLU", "IIM", 10],
  ["HNLU", "Sector 17", 10],
  ["HNLU", "Sector 22", 10],
  ["HNLU", "CBD Railway Station", 10],
  ["HNLU", "Office Complex Block A B", 10],
  ["HNLU", "Rawatpura Sarkar University", 10],
  ["Balco Medical Center", "Indravati Bhavan", 10],
  ["Balco Medical Center", "Mahanadi Bhavan", 10],
  ["Balco Medical Center", "CBD", 10],
  ["Balco Medical Center", "Sector 15", 10],
  ["Balco Medical Center", "IIM", 10],
  ["Balco Medical Center", "Sector 17", 10],
  ["Balco Medical Center", "Sector 22", 10],
  ["Balco Medical Center", "CBD Railway Station", 10],
  ["Balco Medical Center", "Office Complex Block A B", 10],
  ["Balco Medical Center", "Rawatpura Sarkar University", 10],
  ["Sector 30", "Indravati Bhavan", 10],
  ["Sector 30", "Mahanadi Bhavan", 10],
  ["Sector 30", "North Block", 10],
  ["Sector 30", "CBD", 10],
  ["Sector 30", "Sector 15", 10],
  ["Sector 30", "Sector 17", 10],
  ["Sector 30", "Sector 22", 10],
  ["Sector 30", "CBD Railway Station", 10],
  ["Sector 30", "Office Complex Block A B", 10],
  ["Sector 30", "Rawatpura Sarkar University", 10],
  ["Sector 30", "HNLU Gate", 10],
  ["Sector 30", "NH 30 Chowk", 10],
  ["Sector 30", "Muktangan", 10],
  ["Sector 29", "Sector 15", 10],
  ["Sector 29", "Satya Sai Hospital", 10],
  ["Sector 29", "Sector 22", 10],
  ["Sector 29", "Rawatpura Sarkar University", 10],
  ["Sector 29", "NH 30 Chowk", 10],
  ["Sector 27", "Sector 15", 10],
  ["Sector 27", "Satya Sai Hospital", 10],
  ["Sector 27", "Sector 22", 10],
  ["Sector 27", "Rawatpura Sarkar University", 10],
  ["Sector 27", "NH 30 Chowk", 10],
  ["South Block", "IIM", 10],
  ["South Block", "Satya Sai Hospital", 10],
  ["South Block", "Stadium", 10],
  ["South Block", "Jungle Safari", 10],
  ["South Block", "HNLU Gate", 10],
  ["South Block", "NH 30 Chowk", 10],
  ["South Block", "Muktangan", 10],
  ["Indravati Bhavan", "Sector 15", 10],
  ["Indravati Bhavan", "Satya Sai Hospital", 10],
  ["Indravati Bhavan", "Sector 22", 10],
  ["Indravati Bhavan", "Jungle Safari", 10],
  ["Indravati Bhavan", "HNLU Gate", 10],
  ["Indravati Bhavan", "IIIT", 10],
  ["Indravati Bhavan", "Muktangan", 10],
  ["Mahanadi Bhavan", "Satya Sai Hospital", 10],
  ["Mahanadi Bhavan", "Sector 22", 10],
  ["Mahanadi Bhavan", "Jungle Safari", 10],
  ["Mahanadi Bhavan", "HNLU Gate", 10],
  ["Mahanadi Bhavan", "IIIT", 10],
  ["Mahanadi Bhavan", "Muktangan", 10],
  ["North Block", "IIM", 10],
  ["North Block", "Stadium", 10],
  ["North Block", "Nawagaon", 10],
  ["North Block", "Jungle Safari", 10],
  ["North Block", "HNLU Gate", 10],
  ["North Block", "IIIT", 10],
  ["North Block", "Muktangan", 10],
  ["Ekatm Path", "IIM", 10],
  ["Ekatm Path", "Satya Sai Hospital", 10],
  ["Ekatm Path", "Stadium", 10],
  ["Ekatm Path", "Nawagaon", 10],
  ["Ekatm Path", "Jungle Safari", 10],
  ["Ekatm Path", "HNLU Gate", 10],
  ["Ekatm Path", "IIIT", 10],
  ["Ekatm Path", "Muktangan", 10],
  ["CBD", "Satya Sai Hospital", 10],
  ["CBD", "Stadium", 10],
  ["CBD", "Jungle Safari", 10],
  ["CBD", "IIIT", 10],
  ["Sector 15", "Satya Sai Hospital", 10],
  ["Sector 15", "Sector 27-29 Mid", 10],
  ["Telibandha", "Raipur Railway Station", 10],
  ["DKS Bhawan", "Agriculture College", 10],
  ["IIM", "Sector 17", 10],
  ["IIM", "Mantri Aawas", 10],
  ["IIM", "Rakhi Village", 10],
  ["IIM", "Jungle Safari", 10],
  ["IIM", "HNLU Gate", 10],
  ["IIM", "IIIT", 10],
  ["IIM", "Muktangan", 10],
  ["Sector 17", "Stadium", 10],
  ["Sector 17", "Nawagaon", 10],
  ["Sector 17", "Jungle Safari", 10],
  ["Sector 17", "HNLU Gate", 10],
  ["Sector 17", "IIIT", 10],
  ["Sector 17", "Muktangan", 10],
  ["Satya Sai Hospital", "CBD Railway Station", 10],
  ["Satya Sai Hospital", "Office Complex Block A B", 10],
  ["Satya Sai Hospital", "Mantri Aawas", 10],
  ["Satya Sai Hospital", "Rakhi Village", 10],
  ["Satya Sai Hospital", "Sector 27-29 Mid", 10],
  ["Stadium", "Office Complex Block A B", 10],
  ["Nawagaon", "CBD Railway Station", 10],
  ["Sector 22", "Rakhi Village", 10],
  ["Sector 22", "Sector 27-29 Mid", 10],
  ["Sector 22", "Jungle Safari", 10],
  ["Sector 22", "HNLU Gate", 10],
  ["CBD Railway Station", "Jungle Safari", 10],
  ["CBD Railway Station", "HNLU Gate", 10],
  ["Office Complex Block A B", "Jungle Safari", 10],
  ["Office Complex Block A B", "HNLU Gate", 10],
  ["Office Complex Block A B", "Muktangan", 10],
  ["Mantri Aawas", "Jungle Safari", 10],
  ["Mantri Aawas", "HNLU Gate", 10],
  ["Mantri Aawas", "NH 30 Chowk", 10],
  ["Mantri Aawas", "Muktangan", 10],
  ["Rakhi Village", "Jungle Safari", 10],
  ["Rakhi Village", "HNLU Gate", 10],
  ["Rakhi Village", "NH 30 Chowk", 10],
  ["Sector 27-29 Mid", "NH 30 Chowk", 10],
  ["Jungle Safari", "Thanaud", 10],
  ["Jungle Safari", "NH 30 Chowk", 10],
  ["Rawatpura Sarkar University", "HNLU Gate", 10],
  ["Rawatpura Sarkar University", "NH 30 Chowk", 10],
  ["Rawatpura Sarkar University", "IIIT", 10],
  ["Rawatpura Sarkar University", "Muktangan", 10],
  ["Thanaud", "HNLU Gate", 10],
  ["NH 30 Chowk", "Muktangan", 10],

  // ---- ₹15 ----
  ["HNLU", "Satya Sai Hospital", 15],
  ["HNLU", "Stadium", 15],
  ["HNLU", "Nawagaon", 15],
  ["HNLU", "Thanaud", 15],
  ["Balco Medical Center", "Satya Sai Hospital", 15],
  ["Balco Medical Center", "Stadium", 15],
  ["Balco Medical Center", "Nawagaon", 15],
  ["Balco Medical Center", "Thanaud", 15],
  ["Sector 30", "Satya Sai Hospital", 15],
  ["Sector 30", "Stadium", 15],
  ["Sector 30", "Nawagaon", 15],
  ["Sector 30", "Thanaud", 15],
  ["Sector 29", "Stadium", 15],
  ["Sector 29", "Nawagaon", 15],
  ["Sector 29", "Thanaud", 15],
  ["Sector 27", "Stadium", 15],
  ["Sector 27", "Nawagaon", 15],
  ["Sector 27", "Thanaud", 15],
  ["South Block", "Agriculture College", 15],
  ["South Block", "Nawagaon", 15],
  ["South Block", "Rawatpura Sarkar University", 15],
  ["South Block", "Thanaud", 15],
  ["Indravati Bhavan", "IIM", 15],
  ["Indravati Bhavan", "Stadium", 15],
  ["Indravati Bhavan", "Nawagaon", 15],
  ["Indravati Bhavan", "Rawatpura Sarkar University", 15],
  ["Indravati Bhavan", "NH 30 Chowk", 15],
  ["Mahanadi Bhavan", "IIM", 15],
  ["Mahanadi Bhavan", "Stadium", 15],
  ["Mahanadi Bhavan", "Nawagaon", 15],
  ["Mahanadi Bhavan", "Rawatpura Sarkar University", 15],
  ["Mahanadi Bhavan", "NH 30 Chowk", 15],
  ["North Block", "Agriculture College", 15],
  ["North Block", "Rawatpura Sarkar University", 15],
  ["North Block", "NH 30 Chowk", 15],
  ["Ekatm Path", "Agriculture College", 15],
  ["Ekatm Path", "Rawatpura Sarkar University", 15],
  ["Ekatm Path", "Thanaud", 15],
  ["Ekatm Path", "NH 30 Chowk", 15],
  ["CBD", "Agriculture College", 15],
  ["CBD", "IIM", 15],
  ["CBD", "Nawagaon", 15],
  ["CBD", "Rawatpura Sarkar University", 15],
  ["CBD", "HNLU Gate", 15],
  ["CBD", "NH 30 Chowk", 15],
  ["CBD", "Muktangan", 15],
  ["Sector 15", "Telibandha", 15],
  ["Sector 15", "Agriculture College", 15],
  ["Sector 15", "IIM", 15],
  ["Sector 15", "Stadium", 15],
  ["Sector 15", "Nawagaon", 15],
  ["Sector 15", "Jungle Safari", 15],
  ["Sector 15", "HNLU Gate", 15],
  ["Sector 15", "NH 30 Chowk", 15],
  ["Sector 15", "IIIT", 15],
  ["Sector 15", "Muktangan", 15],
  ["Raipur Railway Station", "Agriculture College", 15],
  ["Agriculture College", "Sector 17", 15],
  ["Agriculture College", "Sector 22", 15],
  ["Agriculture College", "CBD Railway Station", 15],
  ["Agriculture College", "Office Complex Block A B", 15],
  ["Agriculture College", "Mantri Aawas", 15],
  ["IIM", "Sector 22", 15],
  ["IIM", "CBD Railway Station", 15],
  ["IIM", "Office Complex Block A B", 15],
  ["IIM", "Rawatpura Sarkar University", 15],
  ["IIM", "NH 30 Chowk", 15],
  ["Sector 17", "Rawatpura Sarkar University", 15],
  ["Sector 17", "NH 30 Chowk", 15],
  ["Satya Sai Hospital", "Sector 22", 15],
  ["Satya Sai Hospital", "Jungle Safari", 15],
  ["Satya Sai Hospital", "HNLU Gate", 15],
  ["Satya Sai Hospital", "IIIT", 15],
  ["Satya Sai Hospital", "Muktangan", 15],
  ["Stadium", "Sector 22", 15],
  ["Stadium", "CBD Railway Station", 15],
  ["Stadium", "Mantri Aawas", 15],
  ["Stadium", "Rakhi Village", 15],
  ["Stadium", "Sector 27-29 Mid", 15],
  ["Stadium", "IIIT", 15],
  ["Nawagaon", "Sector 22", 15],
  ["Nawagaon", "Office Complex Block A B", 15],
  ["Nawagaon", "Mantri Aawas", 15],
  ["Nawagaon", "Rakhi Village", 15],
  ["Nawagaon", "Sector 27-29 Mid", 15],
  ["Sector 22", "Rawatpura Sarkar University", 15],
  ["Sector 22", "NH 30 Chowk", 15],
  ["CBD Railway Station", "Rawatpura Sarkar University", 15],
  ["CBD Railway Station", "NH 30 Chowk", 15],
  ["Office Complex Block A B", "NH 30 Chowk", 15],
  ["Mantri Aawas", "Rawatpura Sarkar University", 15],
  ["Rakhi Village", "Rawatpura Sarkar University", 15],
  ["Rakhi Village", "Thanaud", 15],
  ["Sector 27-29 Mid", "Rawatpura Sarkar University", 15],
  ["Sector 27-29 Mid", "Thanaud", 15],
  ["Thanaud", "NH 30 Chowk", 15],
  ["Thanaud", "IIIT", 15],
  ["Thanaud", "Muktangan", 15],

  // ---- ₹25 ----
  ["HNLU", "Agriculture College", 25],
  ["Balco Medical Center", "Agriculture College", 25],
  ["Sector 30", "Agriculture College", 25],
  ["Sector 29", "Agriculture College", 25],
  ["Sector 27", "Agriculture College", 25],
  ["South Block", "Telibandha", 25],
  ["Indravati Bhavan", "Agriculture College", 25],
  ["Indravati Bhavan", "Thanaud", 25],
  ["Mahanadi Bhavan", "Agriculture College", 25],
  ["Mahanadi Bhavan", "Thanaud", 25],
  ["North Block", "Telibandha", 25],
  ["North Block", "Thanaud", 25],
  ["Ekatm Path", "Telibandha", 25],
  ["CBD", "Telibandha", 25],
  ["CBD", "Thanaud", 25],
  ["Sector 15", "DKS Bhawan", 25],
  ["Sector 15", "Rawatpura Sarkar University", 25],
  ["Sector 15", "Thanaud", 25],
  ["Telibandha", "Sector 17", 25],
  ["Telibandha", "Sector 22", 25],
  ["Telibandha", "CBD Railway Station", 25],
  ["Telibandha", "Office Complex Block A B", 25],
  ["Agriculture College", "Satya Sai Hospital", 25],
  ["Agriculture College", "Rakhi Village", 25],
  ["Agriculture College", "Sector 27-29 Mid", 25],
  ["Agriculture College", "IIIT", 25],
  ["IIM", "Satya Sai Hospital", 25],
  ["IIM", "Stadium", 25],
  ["IIM", "Nawagaon", 25],
  ["IIM", "Thanaud", 25],
  ["Sector 17", "Thanaud", 25],
  ["Satya Sai Hospital", "Rawatpura Sarkar University", 25],
  ["Satya Sai Hospital", "NH 30 Chowk", 25],
  ["Stadium", "Jungle Safari", 25],
  ["Stadium", "HNLU Gate", 25],
  ["Stadium", "NH 30 Chowk", 25],
  ["Stadium", "Muktangan", 25],
  ["Nawagaon", "Jungle Safari", 25],
  ["Nawagaon", "HNLU Gate", 25],
  ["Nawagaon", "NH 30 Chowk", 25],
  ["Nawagaon", "IIIT", 25],
  ["Nawagaon", "Muktangan", 25],
  ["Sector 22", "Thanaud", 25],
  ["CBD Railway Station", "Thanaud", 25],
  ["Office Complex Block A B", "Rawatpura Sarkar University", 25],
  ["Office Complex Block A B", "Thanaud", 25],
  ["Mantri Aawas", "Thanaud", 25],

  // ---- ₹30 ----
  ["HNLU", "Telibandha", 30],
  ["Balco Medical Center", "Telibandha", 30],
  ["Sector 30", "Telibandha", 30],
  ["Sector 29", "Telibandha", 30],
  ["Sector 29", "DKS Bhawan", 30],
  ["Sector 27", "Telibandha", 30],
  ["Sector 27", "DKS Bhawan", 30],
  ["South Block", "DKS Bhawan", 30],
  ["Indravati Bhavan", "Telibandha", 30],
  ["Indravati Bhavan", "DKS Bhawan", 30],
  ["Mahanadi Bhavan", "Telibandha", 30],
  ["Mahanadi Bhavan", "DKS Bhawan", 30],
  ["North Block", "DKS Bhawan", 30],
  ["North Block", "Raipur Railway Station", 30],
  ["Ekatm Path", "DKS Bhawan", 30],
  ["Ekatm Path", "Raipur Railway Station", 30],
  ["CBD", "DKS Bhawan", 30],
  ["CBD", "Raipur Railway Station", 30],
  ["Sector 15", "Raipur Railway Station", 30],
  ["Telibandha", "Satya Sai Hospital", 30],
  ["Telibandha", "Mantri Aawas", 30],
  ["Telibandha", "Rakhi Village", 30],
  ["Telibandha", "Sector 27-29 Mid", 30],
  ["Telibandha", "IIIT", 30],
  ["DKS Bhawan", "Sector 17", 30],
  ["DKS Bhawan", "Sector 22", 30],
  ["DKS Bhawan", "CBD Railway Station", 30],
  ["DKS Bhawan", "Office Complex Block A B", 30],
  ["DKS Bhawan", "Mantri Aawas", 30],
  ["DKS Bhawan", "Rakhi Village", 30],
  ["DKS Bhawan", "Sector 27-29 Mid", 30],
  ["Raipur Railway Station", "Sector 17", 30],
  ["Raipur Railway Station", "Sector 22", 30],
  ["Raipur Railway Station", "CBD Railway Station", 30],
  ["Raipur Railway Station", "Office Complex Block A B", 30],
  ["Agriculture College", "IIM", 30],
  ["Agriculture College", "Stadium", 30],
  ["Agriculture College", "Nawagaon", 30],
  ["Agriculture College", "Jungle Safari", 30],
  ["Agriculture College", "HNLU Gate", 30],
  ["Agriculture College", "NH 30 Chowk", 30],
  ["Agriculture College", "Muktangan", 30],
  ["Satya Sai Hospital", "Thanaud", 30],
  ["Stadium", "Rawatpura Sarkar University", 30],
  ["Stadium", "Thanaud", 30],
  ["Nawagaon", "Rawatpura Sarkar University", 30],
  ["Nawagaon", "Thanaud", 30],

  // ---- ₹40 ----
  ["HNLU", "DKS Bhawan", 40],
  ["HNLU", "Raipur Railway Station", 40],
  ["Balco Medical Center", "DKS Bhawan", 40],
  ["Balco Medical Center", "Raipur Railway Station", 40],
  ["Sector 30", "DKS Bhawan", 40],
  ["Sector 30", "Raipur Railway Station", 40],
  ["Sector 29", "Raipur Railway Station", 40],
  ["Sector 27", "Raipur Railway Station", 40],
  ["South Block", "Raipur Railway Station", 40],
  ["Indravati Bhavan", "Raipur Railway Station", 40],
  ["Mahanadi Bhavan", "Raipur Railway Station", 40],
  ["Telibandha", "IIM", 40],
  ["Telibandha", "Stadium", 40],
  ["Telibandha", "Nawagaon", 40],
  ["Telibandha", "Jungle Safari", 40],
  ["Telibandha", "HNLU Gate", 40],
  ["Telibandha", "NH 30 Chowk", 40],
  ["Telibandha", "Muktangan", 40],
  ["DKS Bhawan", "Satya Sai Hospital", 40],
  ["DKS Bhawan", "Stadium", 40],
  ["DKS Bhawan", "Jungle Safari", 40],
  ["DKS Bhawan", "HNLU Gate", 40],
  ["DKS Bhawan", "IIIT", 40],
  ["DKS Bhawan", "Muktangan", 40],
  ["Raipur Railway Station", "Satya Sai Hospital", 40],
  ["Raipur Railway Station", "Mantri Aawas", 40],
  ["Raipur Railway Station", "Rakhi Village", 40],
  ["Raipur Railway Station", "Sector 27-29 Mid", 40],
  ["Raipur Railway Station", "IIIT", 40],
  ["Agriculture College", "Rawatpura Sarkar University", 40],
  ["Agriculture College", "Thanaud", 40],

  // ---- ₹45 ----
  ["Telibandha", "Rawatpura Sarkar University", 45],
  ["Telibandha", "Thanaud", 45],
  ["DKS Bhawan", "IIM", 45],
  ["DKS Bhawan", "Nawagaon", 45],
  ["DKS Bhawan", "Rawatpura Sarkar University", 45],
  ["DKS Bhawan", "Thanaud", 45],
  ["DKS Bhawan", "NH 30 Chowk", 45],
  ["Raipur Railway Station", "IIM", 45],
  ["Raipur Railway Station", "Stadium", 45],
  ["Raipur Railway Station", "Nawagaon", 45],
  ["Raipur Railway Station", "Jungle Safari", 45],
  ["Raipur Railway Station", "Rawatpura Sarkar University", 45],
  ["Raipur Railway Station", "Thanaud", 45],
  ["Raipur Railway Station", "HNLU Gate", 45],
  ["Raipur Railway Station", "NH 30 Chowk", 45],
  ["Raipur Railway Station", "Muktangan", 45],
];

/** Mirrors the pair list into a dense, symmetric lookup. */
const buildFareTable = (
  pairs: readonly FarePair[]
): Record<StopName, Record<StopName, number>> => {
  const table = {} as Record<StopName, Record<StopName, number>>;

  for (const stop of STOPS) {
    table[stop] = {} as Record<StopName, number>;
    table[stop][stop] = 0;
  }

  for (const [from, to, fare] of pairs) {
    table[from][to] = fare;
    table[to][from] = fare;
  }

  return table;
};

export const FARE_TABLE = buildFareTable(FARE_PAIRS);

/**
 * Fare between two stops in rupees, or null where none is published.
 *
 * Tolerant of partial input because booking UIs call it while the passenger
 * is still choosing: unknown or empty stops return null rather than throwing.
 * Null is not zero - zero is the real fare for travelling nowhere, while null
 * means the journey cannot be priced and so cannot be sold.
 */
export const calculateFare = (from: string, to: string): number | null => {
  if (!isStopName(from) || !isStopName(to)) return null;
  if (from === to) return 0;

  return FARE_TABLE[from][to] ?? null;
};

export interface FareBand {
  fare: number;
  destinations: StopName[];
}

/**
 * Fares from a single origin, grouped by price and ordered cheapest first.
 *
 * Powers the public fares page, which previously hardcoded its own prices and
 * had drifted out of step with the fare table.
 */
export const getFareBandsFrom = (origin: StopName): FareBand[] => {
  const byFare = new Map<number, StopName[]>();

  for (const stop of STOPS) {
    if (stop === origin) continue;

    const fare = FARE_TABLE[origin][stop];
    if (fare === undefined) continue;

    const bucket = byFare.get(fare);
    if (bucket) bucket.push(stop);
    else byFare.set(fare, [stop]);
  }

  return [...byFare.entries()]
    .sort(([a], [b]) => a - b)
    .map(([fare, destinations]) => ({ fare, destinations }));
};
